---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Feeds aggregator API"
  termsOfService: "https://github.com/frost-tb-voo"
basePath: "/api"
schemes:
- "http"
- "https"
paths:
  /feeds:
    get:
      operationId: "readFeed"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema: {}
        400:
          description: "Invalid params supplied"
      x-swagger-router-controller: "Default"
    post:
      operationId: "createFeed"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Feed"
      responses:
        201:
          description: "successful operation"
      x-swagger-router-controller: "Default"
  /feeds/{feed_id}:
    put:
      operationId: "updateFeed"
      produces:
      - "application/json"
      parameters:
      - name: "feed_id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Feed"
      responses:
        201:
          description: "successful operation"
        400:
          description: "Invalid params supplied"
        404:
          description: "Feed not found"
      x-swagger-router-controller: "Default"
    delete:
      operationId: "deleteFeed"
      produces:
      - "application/json"
      parameters:
      - name: "feed_id"
        in: "path"
        required: true
        type: "string"
      responses:
        201:
          description: "successful operation"
        400:
          description: "Invalid params supplied"
        404:
          description: "Feed not found"
      x-swagger-router-controller: "Default"
  /feeds/rss:
    get:
      operationId: "rss"
      produces:
      - "application/rss+xml"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
        400:
          description: "Invalid params supplied"
      x-swagger-router-controller: "Default"
  /feeds/sync:
    post:
      operationId: "sync"
      produces:
      - "application/json"
      parameters: []
      responses:
        201:
          description: "successful operation"
          schema:
            type: "string"
        400:
          description: "Invalid params supplied"
      x-swagger-router-controller: "Default"
definitions:
  Feed:
    type: "object"
    properties:
      feed_id:
        type: "string"
        example: "reddit"
      url:
        type: "string"
        example: "https://www.reddit.com/.rss"
      image_url:
        type: "string"
        example: "https://www.reddit.com/favicon.ico"
      description:
        type: "string"
        example: "reddit"
      blacklist:
        type: "array"
        items:
          type: "string"
          example: "advertise*com*"
      by:
        type: "string"
        example: "someone who added this feed"
    xml:
      name: "Feed"
